site_name: Passivbot
site_url: https://www.passivbot.com
repo_url: https://github.com/enarjord/passivbot
use_directory_urls: True
docs_dir: docs
nav:
  - Home: README.md
  - Configuration: configuration.md
  - Running live: live.md
  - Backtesting: backtesting.md
  - Optimizing: optimizing.md
theme:
  name: material
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  custom_dir: 'docs/overrides'
  palette:
    primary: 'blue grey'
    accent: 'tear'
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: True
  - pymdownx.inlinehilite
  - pymdownx.superfences
extra:
  version:
    provider: mike
